manifest:
  projects:
    - name: zephyr
    url: https://github.com/zephyrproject-rtos/zephyr
    revison: 413b789deb391d3a37d06b463288a5fe765ee57e
    import:
      name-allowlist:
        - cmsis_6
        - hal_infineon
        - mbedtls
        - hal_rpi_pico
    
